service: dio-serverless-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: ${file(./properties.yml):region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - ${file(./properties.yml):dynamoDBResource}ItemTable

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    events:
      - http:
          path: /item
          method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      - http:
          path: /item/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /item/{id}
          method: put

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
